name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission
        run: chmod u+x gradlew

      - name: Run build and test
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4

  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission
        run: chmod u+x gradlew

      - name: Run GameTest
        run: ./gradlew runGameTestServer

      - name: Check report
        run: |
          ! test -d "run-server/crash-reports"

      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          path: |
            run-server/crash-reports/*
          name: Test-Report-${{ github.run_number }}
